on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - feat/azure-bicep-poc
name: Continuous Deploy
jobs:
  arm-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM Bicep file
      - name: ARM Deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./bicep/main.bicep
          failOnStdErr: false

  # Deploy .Net Core API
  api-deploy:
    needs: arm-deploy
    uses: "KyleMcMaster/payroll-processor/.github/workflows/api-deploy.yml@feat/azure-bicep-poc" #todo update branch

  # Deploy Angular Client
  client-deploy:
    needs: arm-deploy
    uses: "KyleMcMaster/payroll-processor/.github/workflows/client-deploy.yml@feat/azure-bicep-poc"

  # Deploy Azure Functions
  # api-deploy:
  #   needs: arm-deploy
  #   uses: "KyleMcMaster/payroll-processor/.github/workflows/api-deploy.yml@feat/azure-bicep-poc"
